# Generated by Django 4.1.2 on 2022-10-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='count',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
